# Generated by Django 3.1.6 on 2021-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvrCallbackTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ivr_callback_transaction_log',
            },
        ),
        migrations.CreateModel(
            name='WebhookTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_transaction_log',
            },
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Missedcall', 'Inbound Missedcall'), ('Outbound Live Call', 'Outbound Live Call')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Unreachable', 'Unreachable'), ('DND', 'DND'), ('Invalid Number', 'Invalid Number'), ('Rejected', 'Rejected'), ('Busy', 'Busy'), ('Answered', 'Answered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='ivrprompt',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnersystemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grand Father', 'Grand Father'), ('Grand Mother', 'Grand Mother'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodulecontent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
